---
# Lint directives.
lint:

  rules:

    remove:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - REPEATED_FIELD_NAMES_PLURALIZED

  rules_option:
    max_line_length:
      # Enforces a maximum line length
      max_chars: 180
